### ISSUE TITLE
Seems to require object reset/spread babel plugin

### ISSUE THREAD

**Issue by samsch** [infernojs/babel-plugin-inferno#45]
I'm getting this error. It looks like this plugin is outputting code with object spread where JSX spread is used.
```
ERROR in ./src/main.js
Module parse failed: <project-path>/node_modules/babel-loader/lib/index.js!<project-path>/src/main.js Unexpected token (144:4)
You may need an appropriate loader to handle this file type.
| const render = () => {
|   _inferno2.default.render(createVNode(16, _Component2.default, null, null, {
|     ...store.state,
|     ...messagesStore.state,
|     'actions': actions
 @ multi (webpack)-dev-server/client?https://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/main.js
```

If the object spread babel plugin should be required to use this plugin, then I'd expect that to be documented. However, it seems better to compile to current JS, as the JSX plugin used by the React babel preset does.

**Comment by trueadm** [comment]
@samsch I believe this was intentional – you can use `babel-preset` to automatically detect your settings per environment, which should auto do this. This may already be the case, as object spread is already in some browsers such as Chrome and is Stage 3 – https://github.com/tc39/proposal-object-rest-spread.

**Comment by Havunen** [comment]
This plugin is only JSX compiler unlike React preset which is collection of plugins. You can if you want just include rest spread plugin into your compiler pipeline.
